### ISSUE TITLE
calling another $simplert at onConfirm

### ISSUE THREAD

**Issue by arfnn** [mazipan/vue2-simplert-plugin#10]
pakai bahasa indonesia aja ya :smiley: 
cara panggil simplert lain di onConfirm gimana ya?

ketika memanggil konfirmasi() dan klik Ya, maka akan nampilkan simplert lagi

sebelumnya pakai vue2 simplert yg biasa (bukan plugin)
cara ini bisa, tapi di simplert plugin udah gk bisa lagi

maaf gak ada link reproduce

![image](https://user-images.githubusercontent.com/35249342/34705750-b9fffbba-f53d-11e7-9342-13e970a4c5cb.png)

**Comment by mazipan** [comment]
Will try to reproduce first ya.

**Comment by mazipan** [comment]
Tambahkan timeout atau nexTick
```js
setTimeout(() => {
  this.$Simplert.open(obj)
}, 500);
```

Jangan lupa update juga versi nya ke 0.1.0 ya @arfnn 
Thanks... 👍
