### ISSUE TITLE
Error can't resolve 'Vue' on app building

### ISSUE THREAD

**Issue by Insolita** [mazipan/vue2-simplert-plugin#11]
Vue version 2.5.13
plugin version 0.1.0
node version 0.9.4
webpack version 5.6.0
os: archlinux
`
ERROR in ./node_modules/vue2-simplert-plugin/dist/vue2-simplert-plugin.js
Module not found: Error: Can't resolve 'Vue' in '/node_modules/vue2-simplert-plugin/dist'
 @ ./node_modules/vue2-simplert-plugin/dist/vue2-simplert-plugin.js 2:82-96

This dependency was not found:

* Vue in ./node_modules/vue2-simplert-plugin/dist/vue2-simplert-plugin.js

To install it, you can run: npm install --save Vue    

`

Usage as in documentation 

```js
import Vue from 'vue';
...
import Simplert from 'vue2-simplert-plugin';
Vue.use(Simplert);
...

```

**Comment by mazipan** [comment]
Can you raise to latest version ?

**Comment by phelipe** [comment]
Same here.

**Comment by mazipan** [comment]
Do you have made alias to resolve in webpack

```js
resolve: {
    extensions: ['.js', '.json', '.vue'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    }
  },
```

**Comment by phelipe** [comment]
Yes.

**Comment by mazipan** [comment]
I try using in [here](https://github.com/mazipan/explore-github/blob/master/src/pages/About.vue#L67) and work well

**Comment by cybermake** [comment]
No build bugs in windows OS...
Exception throwed only in linux.

For resolve this problem, add next alias to webpack config:

      'Vue$': 'vue/dist/vue.esm.js',

See my solution:

resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      'Vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    }
