### ISSUE TITLE
Unknown custom element: <simplert> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by ChristianBielak** [mazipan/vue2-simplert-plugin#19]
Always get the message

Unknown custom element: <simplert> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

when trying to use Simplert with laravel. The Plugin is regsitered in the main.js file.

**Comment by elceka** [comment]
Hi, I have same Vue warning in console.
The project has been generated from vue-cli, is based on webpack.
VueJS version is 2.6.10, Vue2 Simplert plugin version is 0.5.3

**Comment by dmotors** [comment]
After trying different version moving from newest to oldest, I discovered a working version:

0.4.1

So just install it by the follow:
```
npm i vue2-simplert-plugin@0.4.1 --save
```

**Comment by Berkmann18** [comment]
Same problem here which leads to another error ("vue.runtime.esm.js?2b0e:619 [Vue warn]: Failed to mount component: template or render function not defined.") when adding:
```js
import Simplert from "vue2-simplert-plugin";

export default {
  name: "App",
  components: {
    //...
    Simplert
  },
```

**Comment by paulm17** [comment]
Same here.  I have an old project, seemed to work fine when I used it last.

Just started on a new project and I keep getting:

    [Vue warn]: Failed to mount component: template or render function not defined.

Will keep an eye on this, but going to be looking at other components now....

**Comment by LobotheStark** [comment]
> After trying different versions moving from newest to oldest, I discovered a working version:
> 
> 0.4.1
> 
> So just install it by doing the following:
> 
> ```
> npm i vue2-simplert-plugin@0.4.1 --save
> ```

April 2021, you saved me. Thanks.

**Comment by mazipan** [comment]
🔥 on #27
